# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HZIdO8XBQOyY5JyrYjsdAkveXvPba_QK
"""

import pandas as pd
data = pd.read_csv("/content/netflix_titles.csv")
data

data.head()

data.shape

data[data.duplicated()]

data[data.isnull()]

import seaborn as sns

sns.heatmap (data.isnull())

#for "Naruto the Movie 2: Legend of the Stone of Gelel" what is the show id and who is the director of the show?
data[data['title'].isin (['Naruto the Movie 2: Legend of the Stone of Gelel'])]

data[data['title'].str.contains('Naruto the Movie 2: Legend of the Stone of Gelel',na=False)]

#in which year highest number ofthe tv shows&movies were released show with bargraphs
data.dtypes

data['release_year'].isnull().sum()
data = data.dropna(subset=['release_year'])
data['release_year'].value_counts().idxmax()

data[data['release_year'] == data['release_year'].value_counts().idxmax()]['type'].value_counts().plot(kind='bar')#, title='TV Shows vs Movies in Top Release Year', xlabel='Type', ylabel='Count', color=['orange', 'purple'])

#how many movies &tvshows are in the dataset? show with bar graph
data.groupby('type').type.count()
sns.countplot(data['type'])

#show all the moviesthat were released in the year 2000
data[(data['type']=='Movie') & (data['release_year']==2000)]

#show only the title of all shows that were released in india only
data[(data['type']=='Movie')&(data['country']=='India')]['title']

#top 10 directors who gave highest number of tv shows and movies to netflix
data['director'].value_counts().head(10)

data[(data['type'] == 'Movie') & ((data['rating'] == 'TV-MA') | (data['country'] == 'India'))]

#in how many movies /shows Kamal Hassan was cast
data[data ['cast'] .str.contains ('Kamal Hassan',na=False)]

#different ratings defined by netflix? /how many movies got the tv-14 rating ,in japan?  /how many of the tvshows got the 'r' rating ,after year 2018
print(data.rating.nunique())
print(data.rating.unique())

data[(data['type'] == 'Movie') & (data['rating'] == 'TV-14')].shape

data[(data['type'] == 'Movie') & (data['rating'] == 'TV-14') & (data['country'] == 'Japan')].shape

data[(data['type'] == 'Movie') & (data['rating'] == 'R') & (data['release_year'] > 2018)]

data[(data['type'] == 'TV Show') & (data['rating'] == 'R') & (data['release_year'] > 2018)] .shape

# what is the max duration of a movie /tv show on netflix??
data.duration.unique()
data [['Minutes','Units']] = data['duration'].str.split(' ' ,expand =True)
data['Minutes'] = pd.to_numeric(data['Minutes'], errors='coerce')

data.Minutes.max()

#which individual country has the highest no. of tv shows
data_tvshows =data[data['type'] =='TV Show']
data_tvshows.country.value_counts().head(1)

#sorting the data set by year
data.sort_values(by=['release_year']).head(2)
  #data.sort_values(by=['release_year'],ascending = False ).head(2)

#find all the instances where movies with drama and tvshows with kids
data [(data['type'] == 'Movie')  & (data['listed_in'] == 'Dramas') |
(data['type'] == 'TV Show')  & (data['listed_in'] == "Kids' TV")]

data [(data['type'] == 'Movie')  & (data['listed_in'] == 'Dramas')|
(data['type'] == 'TV Show')  & (data['listed_in'] == "Kids' TV")]